### PyTorch-Basics
**PyTorch** is a very popular Deep Learning framework. In this notebook we will go through some of the basics of Tensor data type of **PyTorch**.

Import PyTorch

In [1]:
import numpy as np
import torch

Construct PyTorch Tensors

In [2]:
#From list
l = [1,2,3]
x = torch.tensor(l)
print(x)
print(x.type())

tensor([1, 2, 3])
torch.LongTensor


In [3]:
#From numpy array
arr = np.array([1,2,3])
x = torch.tensor(arr)
print(x)
print(x.type())

tensor([1, 2, 3])
torch.LongTensor


In [4]:
#Directly
x = torch.tensor([1,2,3])
print(x)
print(x.type())

tensor([1, 2, 3])
torch.LongTensor


In [5]:
#Using Tensor constructor
x = torch.Tensor([1,2,3])
print(x)
print(x.type())
print(x.dtype)

tensor([1., 2., 3.])
torch.FloatTensor
torch.float32


Note Tensor constructor makes a tensor of type FloatTensor

Other type of Tensors

In [6]:
#FloatTensor
x = torch.FloatTensor([1,2,3])
print(x)
print(x.type())
print(x.dtype)

tensor([1., 2., 3.])
torch.FloatTensor
torch.float32


In [7]:
#DoubleTensor
x = torch.DoubleTensor([1,2,3])
print(x)
print(x.type())
print(x.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.DoubleTensor
torch.float64


In [8]:
#HalfTensor
x = torch.HalfTensor([1,2,3])
print(x)
print(x.type())
print(x.dtype)

tensor([1., 2., 3.], dtype=torch.float16)
torch.HalfTensor
torch.float16


In [9]:
#BFloat16Tensor
x = torch.BFloat16Tensor([1,2,3])
print(x)
print(x.type())
print(x.dtype)

tensor([1., 2., 3.], dtype=torch.bfloat16)
torch.BFloat16Tensor
torch.bfloat16


In [10]:
#ByteTensor
x = torch.ByteTensor([1,2,3])
print(x)
print(x.type())
print(x.dtype)

tensor([1, 2, 3], dtype=torch.uint8)
torch.ByteTensor
torch.uint8


In [11]:
#CharTensor
x = torch.CharTensor([1,2,3])
print(x)
print(x.type())
print(x.dtype)

tensor([1, 2, 3], dtype=torch.int8)
torch.CharTensor
torch.int8


In [12]:
#Create an empty tensor
torch.empty((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
#Tensor with zeros
torch.zeros((3,4),dtype=torch.int64)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [14]:
#Tensor with ones
torch.ones((3,4),dtype=torch.int64)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [15]:
#Identity matrix
torch.eye(3, dtype=torch.int64)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [16]:
#Using full
torch.full((3,4),99, dtype=torch.int64)

tensor([[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]])

In [17]:
#You can also make tensors from ranges
torch.arange(0,10).reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
x = torch.linspace(0.02,1,50).reshape(10,-1)
x

tensor([[0.0200, 0.0400, 0.0600, 0.0800, 0.1000],
        [0.1200, 0.1400, 0.1600, 0.1800, 0.2000],
        [0.2200, 0.2400, 0.2600, 0.2800, 0.3000],
        [0.3200, 0.3400, 0.3600, 0.3800, 0.4000],
        [0.4200, 0.4400, 0.4600, 0.4800, 0.5000],
        [0.5200, 0.5400, 0.5600, 0.5800, 0.6000],
        [0.6200, 0.6400, 0.6600, 0.6800, 0.7000],
        [0.7200, 0.7400, 0.7600, 0.7800, 0.8000],
        [0.8200, 0.8400, 0.8600, 0.8800, 0.9000],
        [0.9200, 0.9400, 0.9600, 0.9800, 1.0000]])

In [19]:
#Changing datatype of a tensor
#create an int tensor
x = torch.tensor([1,2,3], dtype=torch.int32)
print(x.type())

#change its datatype to float32
x = x.type(torch.float32)
print(x.type())

torch.IntTensor
torch.FloatTensor


One important thing in Deep Learning is having tensorwith random numbers. Below we will make some tensors with random numbers

In [20]:
torch.manual_seed(42)
#Uniform random number
torch.rand((3,4))

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [21]:
#Standard Normal random numbers
torch.randn((3,4))

tensor([[ 2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898],
        [-0.9890,  0.9580,  1.3221,  0.8172]])

In [22]:
#Tensor with random ints
torch.randint(0,10,(3,3))

tensor([[9, 6, 2],
        [0, 6, 2],
        [7, 9, 7]])

There are convienence functions in torch to make random tensors like other tensors

In [23]:
x = torch.ones((3,4), dtype=torch.float32)
print(torch.randint_like(x,low=0,high=10, dtype=torch.int32))
print(torch.randn_like(x))
print(torch.rand_like(x))

tensor([[3, 3, 4, 3],
        [7, 0, 9, 0],
        [9, 6, 9, 5]], dtype=torch.int32)
tensor([[ 0.5312, -0.2483, -0.1735,  1.3850],
        [ 0.7045,  1.2197, -0.6778, -0.5920],
        [-0.6382, -1.9187, -0.6441, -0.6061]])
tensor([[0.1591, 0.7653, 0.2979, 0.8035],
        [0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980]])


## Indexing

Indexing and Slicing of PyTorch Tensors is very similar to numpy indexing and slicing

In [24]:
x = torch.arange(0,12).reshape(3,-1)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [25]:
#Select row 0
x[0]

tensor([0, 1, 2, 3])

In [26]:
#Slice row 0
s = x[0:1]
s
print(s.shape)

torch.Size([1, 4])


In [27]:
#slice column 2
s = x[:,1:2]
s

tensor([[1],
        [5],
        [9]])

In [28]:
#select columnn 2
x[:,1]

#Note again slice gives a 2D tensor but select gives a 1D tensor

tensor([1, 5, 9])

In [29]:
#Slicing with strides
#With stride of 2
x[0::2,0::2]

tensor([[ 0,  2],
        [ 8, 10]])

### Veiw and reshape function

View and reshape are very similar functions, **View** only works on contigous memory and **reshape** is more general.

In [30]:
x.view(4,3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [31]:
x.reshape(4,3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [32]:
#views only work on contigous data
t = x[0::2,0::2]


# t.view(1,4) #Uncomment to see the error
#above will give an error because t is not contigous

In [33]:
#Reshape is more general and will work for everything, but it might sometime copy the data
t.reshape(1,4)

tensor([[ 0,  2,  8, 10]])

### Arithmetic operations on tensors

In [34]:
a = torch.Tensor([1,2,3])
b = torch.Tensor([4,5,6])
print(a)
print(b)
#Addition
print(a + b)
#Another equivalent form is
a.add(b)

tensor([1., 2., 3.])
tensor([4., 5., 6.])
tensor([5., 7., 9.])


tensor([5., 7., 9.])

In [35]:
#Subraction
print(b-a)
b.sub(a)

tensor([3., 3., 3.])


tensor([3., 3., 3.])

In [36]:
#Elementvise multiplication
print(a*b)
a.mul(b)

tensor([ 4., 10., 18.])


tensor([ 4., 10., 18.])

In [37]:
#Elementvise devision
print(a/b)
a.div(b)

tensor([0.2500, 0.4000, 0.5000])


tensor([0.2500, 0.4000, 0.5000])

In [38]:
#Operations with a scalar
#Scalars will broadcast
print("Addition", a + 5)
print("Subtraction", a-5)
print("Multiplication",a*10)
print("Division",a/2.0)

Addition tensor([6., 7., 8.])
Subtraction tensor([-4., -3., -2.])
Multiplication tensor([10., 20., 30.])
Division tensor([0.5000, 1.0000, 1.5000])


In [39]:
#Boradcasting - tensors will broadcast values whenever possible just like numpy
a = torch.Tensor([[1,2,3],[4,5,6]])
b = torch.Tensor([10,11,12])

In [40]:
print(a + b)
print(a-b)
print(a*b)

tensor([[11., 13., 15.],
        [14., 16., 18.]])
tensor([[-9., -9., -9.],
        [-6., -6., -6.]])
tensor([[10., 22., 36.],
        [40., 55., 72.]])


Inplace arithmetic operations.
Tensors also have inplace arithmetic operations

In [41]:
#Underscore operators are short forms for a = a operator b
a.add_(b)
print(a)

a.sub_(b)
print(a)

a.mul_(b)
print(a)

a.div_(b)
print(a)

tensor([[11., 13., 15.],
        [14., 16., 18.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[10., 22., 36.],
        [40., 55., 72.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Matrix operations
**Tensors** support a bunch of matrix operations

In [42]:
#dot product
a = torch.Tensor([1,2,3])
b = torch.Tensor([4,5,6])
#take dot product
a.dot(b)

tensor(32.)

In [43]:
#matrix multiplication
a = a.reshape(3,-1)
b = b.reshape(-1,3)
print("Shape of A=",a.shape)
print("Shape of B=",b.shape)
print(torch.mm(a,b))

#Other way of matrix multiplication
print(a @ b)
print(a.mm(b))

Shape of A= torch.Size([3, 1])
Shape of B= torch.Size([1, 3])
tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])
tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])
tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])


One very common operation in DL is L2Norm, lets try that for a matrix

In [44]:
print(a.norm())

tensor(3.7417)
